spring:
  application:
    name: logbat

  datasource:
    url: jdbc:mysql://localhost:3306/logbat
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
