name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - dev

jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Code Review GPT
        uses: LuizyHub/code-review-gpt@main
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-4o-mini'
          GITHUB_TOKEN: ${{ github.token }}
